# Generated by Django 5.1.4 on 2024-12-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_item_quantity_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='title',
            new_name='item',
        ),
    ]
