# Generated by Django 5.1.4 on 2024-12-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='apartment_address',
            field=models.CharField(default='china', max_length=100),
            preserve_default=False,
        ),
    ]
