# Generated by Django 5.1.4 on 2024-12-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_coupon_usetime_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='useTime',
        ),
        migrations.AddField(
            model_name='coupon',
            name='couponUsed',
            field=models.BooleanField(default=False),
        ),
    ]
